--usuario

INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('PEREZ', '1', 'ROBERTO', '093939393');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ', '2', 'RAUL', '093223333');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ PAZMINO', '11', 'PATRICIO', '092222');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333');
INSERT INTO CLIENTE (APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555');

INSERT INTO DIRECCION (ID, DIRECCION, NOMENCLATURA,CLIENTE_ID) VALUES (1, 'BARVA 123', 'CR', '1');
INSERT INTO DIRECCION (ID, DIRECCION, NOMENCLATURA,CLIENTE_ID) VALUES (2, 'SARCHI 123', 'CR', '2');
INSERT INTO DIRECCION (ID, DIRECCION, NOMENCLATURA,CLIENTE_ID) VALUES (3, 'PANAMA 123', 'PN', '3');

INSERT INTO CUENTA (ID, ISACTIVE,NUMERO, TIPO, CLIENTE_ID) VALUES ('1', true, '00001', 'A', '1');
INSERT INTO CUENTA (ID, ISACTIVE,NUMERO, TIPO, CLIENTE_ID) VALUES ('2', false,'00002', 'A', '2');
INSERT INTO CUENTA (ID, ISACTIVE,NUMERO, TIPO, CLIENTE_ID) VALUES ('3', true,'00003', 'B', '3');
INSERT INTO CUENTA (ID, ISACTIVE, NUMERO, TIPO, CLIENTE_ID) VALUES ('4', true,'00004', 'B', '4');
